name: "ShellCheck"
author: "Ludeeus <hi@ludeeus.dev>"
description: "GitHub action for ShellCheck."
inputs:
  ignore:
    description: 'Paths to ignore when running ShellCheck'
    required: false
    default: ''
  severity:
    description: 'Minimum severity of errors to consider. Options: [error, warning, info, style]'
    required: false
    default: ''
  check_together:
    description: 'Run shellcheck on _all_ files at once, instead of one at a time'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'terminal'
  color: 'gray-dark'
