on: [push, pull_request]
name: 'ShellCheck'
jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Run ShellCheck
      uses: ./
      with:
        ignore: ignore
